---
title: "Sample Size - Grand Bassa Stepped Wedge"
output: word_document
editor_options:
  chunk_output_type: console
---



# Load packages
```{r warning=FALSE, message=FALSE}

# devtools::install_github("Avi-Kenny/simba")

# Load libraries
library(parallel)
library(ggplot2)
library(readxl)
library(magrittr)
library(dplyr)
library(simba)
library(tibble)
library(survival)
library(coxme)
library(tidyr)

```



# Simulation setup
```{r}

# Load functions
# Note: if running this locally in RStudio, you may need to click "Session" >> "Set Working Directory" >> "To Source File Location"
source("R/helpers.R")
source("R/create_dataset.R")
source("R/create_birth_history.R")
source("R/perform_analysis.R")
source("R/take_sample.R")

# Read and transform sampling frame
sampling_frame <- read_excel("data/GrandBassa2020SamplingFrame_truncated.xlsx")
sampling_frame %<>% rowid_to_column("community_id")
sampling_frame %<>% rename(
  "num_hh" = `numHH`,
  "health_district" = `map_health_district`,
  "admin_district" = `map_adm_distri`
)

# Generate population (one for entire simulation)
# !!!!! Speed could be substantially increased by generating population AFTER sampling; but not necessary if "one population per simulation" is used
new_dataset <- FALSE
if (new_dataset) {
  dataset <- create_dataset(
    "sampling_frame" = sampling_frame,
    "program_effect" = 0.25,
    "re_comm_sd" = 0.1,
    "re_tx_sd" = 0.1
  )
  saveRDS(dataset, file="gb_dataset")
} else {
  dataset <- readRDS("gb_dataset")
}

sim <- new_sim()

sim %<>% set_config(
  num_sim = 500,
  datasets = "many",
  parallel = "outer",
  packages = c("magrittr", "dplyr", "tibble", "survival", "coxme", "tidyr")
)

sim %<>% set_levels(
  "sample_size" = c(350, 450)
)

sim %<>% add_constants(
  "sampling_frame" = sampling_frame,
  "dataset" = dataset
)

# Add necessary functions
{
  sim %<>% add_creator(create_dataset)
  sim %<>% add_method(baseline_u5mr)
  sim %<>% add_method(dates_to_cmc)
  sim %<>% add_method(cmc_to_dates)
  sim %<>% add_method(create_birth_history)
  sim %<>% add_method(take_sample)
  sim %<>% add_method(perform_analysis)
}

sim %<>% add_script(
  "script_1",
  function() {
    
    # # Generate population
    # dataset <- create_dataset(
    #   "sampling_frame" = C$sampling_frame,
    #   "program_effect" = 0.25,
    # "re_comm_sd" = 0.1,
    # "re_tx_sd" = 0.1
    # )
    
    # Take a sample from population
    sample <- take_sample(
      "population" = C$dataset,
      "sampling_frame" = C$sampling_frame,
      "n_clusters" = L$sample_size
    )
    
    # Perform statistical analysis
    results <- perform_analysis(
      "sample" = sample,
      "type" = 1
    )
    
    return (results)
    
  }
)

# Run simulation
sim %<>% run("script_1")

# Summarize results
# !!!!! Calculate ICC and DEFF here
sim %>% summary() %>%
  mutate(
    mean_est_pct_reduction_1 = 1-exp(mean_tx_effect_1),
    mean_est_pct_reduction_2 = 1-exp(mean_tx_effect_1),
    power_1 = mean_reject_h0_1,
    power_2 = mean_reject_h0_2
  )

```



# Run simulation
```{r}

# Run simulation
results <- sim %>% run("script_1")

# Summarize results
summary(results, sd=TRUE)

```
